services:
  twitter-app:
    build:
      context: .
    environment:
      - DB_HOST=localhost
      - DB_NAME=twitter
      - DB_USER=postgres
      - DB_PASS=12341234
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_DB=DB_NAME
      - POSTGRES_PASSWORD=DB_PASS

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./backend:/backend
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./backend:/backend
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 5555:5555