# Generated by Django 3.2.16 on 2023-08-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Аватарка')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Полное имя')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение')),
                ('about', models.TextField(blank=True, max_length=255, null=True, verbose_name='О себе')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Веб-сайт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
