# Generated by Django 3.2.16 on 2023-03-24 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(280)]),
        ),
    ]
