# Generated by Django 3.2.16 on 2023-03-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_tweet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='is_updated',
            new_name='updated_at',
        ),
    ]
