# Generated by Django 3.2.16 on 2023-07-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_comment_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
